version: '3'
services:
  db:
    image: postgres:10.2
  web:
    image: yatlab:latest
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - migration
      - db

    env_file:
    - docker.env
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/postgres

  migration:
    image: yatlab:latest
    command: yarn db:migrate
    volumes:
      - .:/code
    depends_on:
      - db

    environment:
      DATABASE_URL: postgres://postgres:@db:5432/postgres
